### ISSUE TITLE
Game specification

### ISSUE THREAD

**Issue by alirezaopmc** [alirezaopmc/hokm#2]
A fully specified document for the game logic and its components is required.

**Comment by alirezaopmc** [comment]
Om on it:

https://docs.google.com/document/d/1F-bi1D779ughSdfeV8699INTK_6-qP9Wya-eMBgqtNg/edit?usp=sharing

**Comment by jaberowski** [comment]
I added most of the rules and game flow to the existing doc

**Comment by alirezaopmc** [comment]
I guess this is fine rn. Later we need a technical documentation.
